# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: BUILDSTAGE
    jobs: 
    - job: Job1 
      steps:
      - script: echo Hello, world edited for review !
        displayName: 'Run a one-line script'
    - job: Job2
      steps:
      - script: echo Hello, world edited for review 2.0!
        displayName: 'Run a one-line script'
  - stage: QAStage
    jobs: 
    - job: Job1 
      steps:
      - script: echo This is the QA  !
        displayName: 'Run a one-line script'
  - stage: PRODStage
    jobs: 
    - job: Job1 
      steps:
      - script: echo This is for production  !
        displayName: 'Run a one-line script'

