# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: BUILDSTAGE
    jobs: 
    - deployment: BUILDDEPLOYJOB
      environment: BUILD
      strategy: 
       runOnce:
        deploy:
          steps:
            - script: echo Deploy to build 
  - stage: PRODUCTION
    jobs: 
    - deployment: PRODDEPLOYJOB
      environment: PROD
      strategy: 
       runOnce:
        deploy:
          steps:
            - script: echo Deploy to build 
  - stage: TEST
    jobs: 
    - deployment: TESTDEPLOYJOB
      environment: TEST
      strategy: 
       runOnce:
        deploy:
          steps:
            - script: echo Deploy to build 
